### ISSUE TITLE
Error in 1.20.2

### ISSUE THREAD

**Issue by SquellyFineOfficiel** [Bounser/Nascraft#9]
My server is in 1.20.2

Here is the log:

> [Server thread/ERROR]: Error occurred while enabling Nascraft v1.6.4 (Is it up to date?)
> java.lang.NoClassDefFoundError: net/kyori/adventure/text/serializer/plain/PlainTextComponentSerializer
> at me.bounser.nascraft.market.resources.Category.<init>(Category.java:36) ~[?:?]
> at me.bounser.nascraft.market.MarketManager.setupItems(MarketManager.java:45) ~[?:?]
> at me.bounser.nascraft.market.MarketManager.<init>(MarketManager.java:37) ~[?:?]
> at me.bounser.nascraft.market.MarketManager.getInstance(MarketManager.java:33) ~[?:?]
> at me.bounser.nascraft.advancedgui.LayoutModifier.updateMainPage(LayoutModifier.java:232) ~[?:?]
> at me.bounser.nascraft.advancedgui.LayoutModifier.onLayoutLoad(LayoutModifier.java:52) ~[?:?]
> at me.leoko.advancedgui.manager.LayoutManager.lambda$registerLayoutExtension$11(LayoutManager.java:258) ~[?:?]
> at java.util.ArrayList.forEach(ArrayList.java:1596) ~[?:?]
> at me.leoko.advancedgui.manager.LayoutManager.registerLayoutExtension(LayoutManager.java:258) ~[?:?]
> at me.bounser.nascraft.advancedgui.LayoutModifier.<init>(LayoutModifier.java:40) ~[?:?]
> at me.bounser.nascraft.advancedgui.LayoutModifier.getInstance(LayoutModifier.java:37) ~[?:?]
> at me.bounser.nascraft.Nascraft.onEnable(Nascraft.java:109) ~[?:?]
> at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[spigot-api-1.20.2-R0.1-SNAPSHOT.jar:?]
> at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.20.2-R0.1-SNAPSHOT.jar:?]
> at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-api-1.20.2-R0.1-SNAPSHOT.jar:?]
> at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:548) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3949-Spigot-2888990-e54f39a]
> at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:462) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3949-Spigot-2888990-e54f39a]
> at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:577) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3949-Spigot-2888990-e54f39a]
> at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:400) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3949-Spigot-2888990-e54f39a]
> at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:250) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3949-Spigot-2888990-e54f39a]
> at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:954) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3949-Spigot-2888990-e54f39a]
> at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:298) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3949-Spigot-2888990-e54f39a]
> at java.lang.Thread.run(Thread.java:1583) ~[?:?]
> Caused by: java.lang.ClassNotFoundException: net.kyori.adventure.text.serializer.plain.PlainTextComponentSerializer
> at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:160) ~[spigot-api-1.20.2-R0.1-SNAPSHOT.jar:?]
> at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:112) ~[spigot-api-1.20.2-R0.1-SNAPSHOT.jar:?]
> at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
> ... 23 more

please help me, i really want to test this plugin!

**Comment by Bounser** [comment]
The only version supported is 1.21
However, there is a 1.20.4-compiled jar in the last release, you can try to use it. Do also note that the last version has a problem with spigot server that I'm currently trying to fix, so you'll have to use paper/purpur in the meanwhile.

**Comment by SquellyFineOfficiel** [comment]
Okay thanks

**Comment by SquellyFineOfficiel** [comment]
Nice it's work in 1.21, paper! Thank you very much!
